// <auto-generated />
using System;
using ChatGbtApp.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatGbtApp.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228100326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ChatGbtApp.Repository.Job", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Applied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryPressureScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("HourlyMax")
                        .HasColumnType("TEXT");

                    b.Property<string>("HourlyMin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IsDistributed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("MacroserviceScore")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Marked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Rejected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Remote")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryIsEstimated")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryOriginalText")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Seniority")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechKeywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url2")
                        .HasColumnType("TEXT");

                    b.HasKey("Url");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
